version: "3"

services:
  db:
    image: postgres:11.2
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: musicians
    ports:
      - 5432:5432
  web:
    image: musicians:latest
    ports:
      - 8000:8000
    depends_on:
      - db
