# Generated by Django 4.1.2 on 2022-10-31 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'title',
                    models.CharField(
                        max_length=250, verbose_name='Название альбома'
                    ),
                ),
                (
                    'release_year',
                    models.PositiveIntegerField(verbose_name='Год выпуска'),
                ),
            ],
        ),
        migrations.CreateModel(
            name='AlbumSong',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('song_number', models.PositiveSmallIntegerField()),
                (
                    'album',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to='main.album'
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(max_length=100, verbose_name='Имя исполнителя'),
                ),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'title',
                    models.CharField(max_length=250, verbose_name='Название песни'),
                ),
                (
                    'album',
                    models.ManyToManyField(
                        through='main.AlbumSong', to='main.album'
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='albumsong',
            name='song',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='main.song'
            ),
        ),
        migrations.AddField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='main.artist'
            ),
        ),
        migrations.AlterUniqueTogether(
            name='albumsong',
            unique_together={('album', 'song_number')},
        ),
    ]
