# Generated by Django 4.1.2 on 2022-11-01 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_album_song_albums'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='albums',
            field=models.ManyToManyField(
                related_name='songs', through='main.AlbumSong', to='main.album'
            ),
        ),
    ]
