# Generated by Django 4.1.2 on 2022-11-01 12:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_song_albums'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='release_year',
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1920),
                    django.core.validators.MaxValueValidator(2022),
                ],
                verbose_name='Год выпуска',
            ),
        ),
    ]
