# Generated by Django 4.1.2 on 2022-11-01 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_album_release_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='main.artist',
                verbose_name='Имя исполнителя',
            ),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=70, verbose_name='Имя исполнителя'),
        ),
    ]
