# Generated by Django 4.1.2 on 2022-11-01 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_album_artist_alter_artist_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={'verbose_name': 'Исполнитель'},
        ),
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='main.artist',
                verbose_name='Исполнитель',
            ),
        ),
        migrations.AlterField(
            model_name='artist',
            name='name',
            field=models.CharField(max_length=70, verbose_name='Исполнитель'),
        ),
    ]
