# Generated by Django 4.1.2 on 2022-11-01 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_artist_options_alter_album_artist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='albums',
                to='main.artist',
                verbose_name='Исполнитель',
            ),
        ),
        migrations.AlterField(
            model_name='albumsong',
            name='song_number',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
