# Generated by Django 4.1.2 on 2022-11-01 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_album_artist_alter_albumsong_song_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumsong',
            name='song_number',
            field=models.PositiveSmallIntegerField(default=15),
            preserve_default=False,
        ),
    ]
